os:
- osx
- linux
language: go
sudo: false
go:
- "1.17"
- "1.18"
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
install:
- go get -t ./...
- go get -t simonwaldherr.de/go/golibs/...
- go get github.com/modocache/gover
script:
- export GO15VENDOREXPERIMENT=1
# test lib with all subfolders
- go test ./...
# test all listed subfolders in verbose mode and create a coverprofile for each
- go test -v -coverprofile=ansi.coverprofile ./ansi
- go test -v -coverprofile=arg.coverprofile ./arg
- go test -v -coverprofile=as.coverprofile ./as
- go test -v -coverprofile=cache.coverprofile ./cache
- go test -v -coverprofile=cachedfile.coverprofile ./cachedfile
- go test -v -coverprofile=channel.coverprofile ./channel
- go test -v -coverprofile=csv.coverprofile ./csv
- go test -v -coverprofile=file.coverprofile ./file
- go test -v -coverprofile=foreach.coverprofile ./foreach
- go test -v -coverprofile=gcurses.coverprofile ./gcurses
- go test -v -coverprofile=gopath.coverprofile ./gopath
- go test -v -coverprofile=graphics.coverprofile ./graphics
- go test -v -coverprofile=log.coverprofile ./log
- go test -v -coverprofile=node.coverprofile ./node
- go test -v -coverprofile=re.coverprofile ./re
- go test -v -coverprofile=regex.coverprofile ./regex
- go test -v -coverprofile=rss.coverprofile ./rss
- go test -v -coverprofile=ssl.coverprofile ./ssl
- go test -v -coverprofile=stack.coverprofile ./stack
- go test -v -coverprofile=structs.coverprofile ./structs
- go test -v -coverprofile=xmath.coverprofile ./xmath
- go test -v -coverprofile=xtime.coverprofile ./xtime
# combine all coverprofiles in one file
- $HOME/gopath/bin/gover
# send coverage details to Coveralls.io
- $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
# generate a coverage detail HTML page
- go tool cover -html=gover.coverprofile -o coverage.html
# print the coverage percentage for each function to the log
- go tool cover -func=gover.coverprofile
# upload the previously generated HTML page to simonwaldherr.de (use $UPLOADSECRET as password)
# - wget --post-file=coverage.html -q -O- "https://simonwaldherr.de/gocover/?repo=golibs&mode=save&key=$UPLOADSECRET&pull=$TRAVIS_PULL_REQUEST"
after_success:
- rm coverage.log
- cp gover.coverprofile coverage.log
- bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov)
notifications:
  email:
    recipients:
    - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
env:
  matrix:
  - secure: DxpD5O3d+UiDqBO4y2qdORXj1EMwUBDEMCUmHg+VDh2LS8Je1SlASVwjeOozMsb1u0HviXcOZZIrEgwaISA7y64HPZzRXfXWtedxKdlElljWd1WqXCbuXkcLP9WKq7cMJ5PCy4zUzNWcMgDp+dCV17VBCul4cPoQrbzzAlq63uk=
